### ISSUE TITLE
Unable to sign out

### ISSUE THREAD

**Issue by ironiemix** [cosmocode/dokuwiki-plugin-authdiscourse#2]
When klicking on "Logout", the user seems to get logged out, but the login information keeps being stored, so when you navigate the wiki afterwards, the users login infos appear again, and the user can do whatever his rights in the wiki allow him to do.
This also happens, when you log out at the Discourse before, and rightfully so, when you klick on "Login" you have to provide your Discourse credentials again - bun then again, navigate to some new wiki page and - voila, you are logged in from before again ;)

**Comment by ironiemix** [comment]
Seems to be a browser issue? When closing an opening the Browser, the cookie is no longer valid and I have to login again.

**Comment by annda** [comment]
Login data was not completely removed from session during logout, which caused automatic re-login. 2b15660430a2ac9238a35f4047fe6fa5b656b19b fixes that.

But note that we do not check with Discourse on every request. So it can happen that a user logs out of the forum and their DokuWiki login is still valid until the session is closed.
