### ISSUE TITLE
Unable to use some groups from discourse for dokuwiki acls

### ISSUE THREAD

**Issue by ironiemix** [cosmocode/dokuwiki-plugin-authdiscourse#3]
Some groups coming from discourse cannot be used for setting up acls in the wiki, because they don't meet dokuwikis rules for group names (I think - is there a documentation about that?).

In detail, all groups with underscore are not working for setting up acls, i.e.  `vertrauensstufe_3`.

I had a similar issue when implementing openSchulportfolio - when authenticating against linuxmuster.net 6 servers, there are groups coming from ldap that start with `p_`, and they also are not usable for dokwuwiki acls. For this reason, I implemeted a dirty patch for authldap when building osp:

https://github.com/OpenSchulportfolio/openschulportfolio/blob/master/patches/lib/plugins/authldap/auth.php.patch

simply by removing the starting `p_` from the LDAP group names, when the according option in the plugin config is set.

Before sending another senseless pull-request for the authdiscourse plugin I wanted to make sure, that it would be a valid solution at all to implement an option in the plugin to substitute all underscores in groupnames coming from discourse? If this seems o.k. to you, a can do this.

**Comment by splitbrain** [comment]
Hmm. That doesn't make sense to me. First of all, underscores are perfectly valid in group and user names, even when using the default authplain backend. Secondly what is and what is not a valid user/group name is completely determined by the authplugin itself. The ACL subsystem does not discriminate against any way of naming.

@annda can you have a look and see if you have any problems with underscores in groupnames and ACLs?

**Comment by annda** [comment]
I looked at the code again and did a quick ACL test with the group `trust_level_1` provided by Discourse.

Underscores should not cause any problems. @ironiemix Can you describe the issues you are having in more detail?

**Comment by ironiemix** [comment]
Situation 1 ist as follows:

```
# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Editing this file by hand shouldn't be necessary. Use the ACL
# Manager interface instead.
#
# If your auth backend allows special char like spaces in groups
# or user names you need to urlencode them (only chars <128, leave
# UTF-8 multibyte chars as is)
#
# none   0
# read   1
# edit   2
# create 4
# upload 8
*	@ALL	1
*	@Members	1
allusers:*	@ALL	1
alt-dokumentation:*	@ALL	0
alt-dokumentation:*	@wikihandbuchteam	16
alt-en:*	@ALL	0
alt-en:*	@wikihandbuchteam	16
anwenderwiki:*	@vertrauensstufe_3	16
anwenderwiki:*	@ALL	1
start	@ALL	1
start	@wikiadmin	2
```
Output of `?do=check` on page `anwenderwiki:server_lmn7:start`
![Auswahl_142](https://user-images.githubusercontent.com/516311/71172028-7e095600-225f-11ea-90db-361162a7f2c4.png)

Situation 2:

Adding the line

```
	  $groups = str_replace("_", "u", $groups);
```
substituting all underscores to `u` in group names around line 55 in `auth.php` of this plugin 

AND 

changing `conf/acl.auth.php` to

```
# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Editing this file by hand shouldn't be necessary. Use the ACL
# Manager interface instead.
#
# If your auth backend allows special char like spaces in groups
# or user names you need to urlencode them (only chars <128, leave
# UTF-8 multibyte chars as is)
#
# none   0
# read   1
# edit   2
# create 4
# upload 8
*	@ALL	1
*	@Members	1
allusers:*	@ALL	1
alt-dokumentation:*	@ALL	0
alt-dokumentation:*	@wikihandbuchteam	16
alt-en:*	@ALL	0
alt-en:*	@wikihandbuchteam	16
anwenderwiki:*	@vertrauensstufeu3	16
anwenderwiki:*	@ALL	1
start	@ALL	1
start	@wikiadmin	2
```
Now a `?do=check` onanwenderwiki:server_lmn7:start`  gives me 

![Auswahl_143](https://user-images.githubusercontent.com/516311/71172416-70a09b80-2260-11ea-80f0-4035df8d3668.png)

seems my dokuwiki is broken? I will try with a fresh installation tomorrow...

**Comment by ironiemix** [comment]
When I look at the screenshots: Could this be a problem with the unset locale in php?

**Comment by annda** [comment]
First of all, the group names in `acl.auth.php` should be encoded, in your case `@vertrauensstufe%5f3`. Normally this would be handled by the admin tool, but it seems you edit the file directly. Please check if url encoding solves the problem.

**Comment by ironiemix** [comment]
> First of all, the group names in `acl.auth.php` should be encoded, in your case `@vertrauensstufe%5f3`. Normally this would be handled by the admin tool, but it seems you edit the file directly. Please check if url encoding solves the problem.

Will do that tomorrow. This wiki ist quite over 10 years old, it is very wellm possible, that some thi

**Comment by ironiemix** [comment]
Closed accidentally, will add my further findings tomorrow.

**Comment by ironiemix** [comment]
> First of all, the group names in `acl.auth.php` should be encoded, in your case `@vertrauensstufe%5f3`. Normally this would be handled by the admin tool, but it seems you edit the file directly. Please check if url encoding solves the problem.

It totally does. So closing this issue, and again, sorry for bothering you and thanks - learned a lot again ;)
